<bug>
          <bug_id>1743</bug_id>
          
          <creation_ts>2008-12-17 11:37:00 +0100</creation_ts>
          <short_desc>Interface:testInterface test fails in Chrome</short_desc>
          <delta_ts>2014-03-03 15:23:58 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>app.testrunner</component>
          <version>unspecified</version>
          <rep_platform>Chrome</rep_platform>
          <op_sys>Windows</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>0.8.3</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Daniel Wagner">daniel.wagner</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>Chrome</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>6983</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2008-12-17 11:37:34 +0100</bug_when>
            <thetext>This test only fails in the source version.

qx.test.Interface:testInterface
Error message is: 
: The raised exception does not have the expected type! function Error() { [native code] }
Stack trace:
qx.core.AssertionError:constructor
qx.core.AssertionError:constructor wrapper
function (condition, comment, msg)
function (callback, exception, re, msg)
qx.core.MAssert:assertException
qx.test.Interface:testInterface
function ()
qx.dev.unit.TestResult:run
qx.dev.unit.TestFunction:run
qx.dev.unit.TestLoader:runTests
function runtest()
function (e)
undefined:constructor
function wrappedFunction()
function (target,event)
function (target,type,clazz,args)
qx.core.Object:fireEvent
qx.event.Timer:_oninterval
function (event)</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7009</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2008-12-17 11:58:08 +0100</bug_when>
            <thetext>*** Bug 1749 has been marked as a duplicate of this bug. ***</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>8883</commentid>
            <who name="Andreas Ecker">qooxdoo</who>
            <bug_when>2009-03-24 19:20:51 +0100</bug_when>
            <thetext>Still an issue in latest Chromes?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>9142</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2009-04-03 16:05:18 +0200</bug_when>
            <thetext>The test hasn&#39;t failed since Chrome was added to the automated tests.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>38217</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:23:58 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>