<bug>
          <bug_id>2751</bug_id>
          
          <creation_ts>2009-09-04 10:12:00 +0200</creation_ts>
          <short_desc>Exception when using Selenium IDE</short_desc>
          <delta_ts>2012-05-16 09:40:35 +0200</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>contrib</product>
          <component>Simulator</component>
          <version>trunk</version>
          <rep_platform>Firefox</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>INVALID</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>unspecified</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Daniel Wagner">daniel.wagner</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="Daniel Wagner">daniel.wagner</qa_contact>
          <cf_browser>Firefox</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>11882</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2009-09-04 10:12:21 +0200</bug_when>
            <thetext>Guilherme Adolfi reports:

I&#39;m getting this error when navigation throw the Selenium IDE commands:

[Exception... &quot;&#39;JavaScript component does not have a method named: &quot;getImageAt&quot;&#39; when calling method: [nsIAutoCompleteResult::getImageAt]&quot; nsresult: &quot;0x80570030 (NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED)&quot; location: &quot;&lt;unknown&gt;&quot; data: no]

3) I&#39;ve to change the qx.core.Asserts:451:
+ array.join(&quot;, &quot;) + &quot;&#39;&quot; 

to

+ &quot;&#39;&quot;

Because when starting my app with selenium IDE opened I was getting this error:

uncaught exception: [Exception... &quot;Security Manager vetoed action&quot; nsresult: &quot;0x80570027 (NS_ERROR_XPC_SECURITY_MANAGER_VETO)&quot; location: &quot;JS frame :: http://localhost/qooxdoo/framework/source/class/qx/core/Assert.js :: anonymous :: line 451&quot; data: no]</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>13148</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2009-10-13 10:43:34 +0200</bug_when>
            <thetext>This exception is thrown even when the qooxdoo Selenium extensions are not loaded and the currently active tab does not contain a qooxdoo application, so it seems to be a problem with Selenium IDE itself.</thetext>
          </long_desc>
      
      

    </bug>