<bug>
          <bug_id>4442</bug_id>
          
          <creation_ts>2010-12-07 09:36:00 +0100</creation_ts>
          <short_desc>qx.html.Element#moveTo links to &quot;Error&quot; in Throws Section</short_desc>
          <delta_ts>2014-03-03 15:20:55 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>app.apiviewer.desktop</component>
          <version>1.2.1</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P4</priority>
          <bug_severity>minor</bug_severity>
          <target_milestone>1.3.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Thomas Herchenroeder">thron7</reporter>
          <assigned_to name="Gabriel Munteanu">jajalinux</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>21796</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2010-12-07 09:36:33 +0100</bug_when>
            <thetext>But if you click on that link you get a &quot;class not found&quot; alert.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>21825</commentid>
            <who name="Gabriel Munteanu">jajalinux</who>
            <bug_when>2010-12-07 12:42:28 +0100</bug_when>
            <thetext>it raises &quot;class not found&quot; because &quot;Error&quot; is not a qooxdoo class but a javascript Object. shall I leave it unlinked, or put a link to an external resource where Error is defined ?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>21828</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2010-12-07 13:37:06 +0100</bug_when>
            <thetext>Gabi, as the issue is not in the particuluar method comment, but a general issue in the Apiviewer code, we move it to the next release, so don&#39;t fix it for 1.2.2.

-&gt; 1.3.1</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>22020</commentid>
            <who name="Gabriel Munteanu">jajalinux</who>
            <bug_when>2010-12-17 09:36:48 +0100</bug_when>
            <thetext>fixed on trunk with rev. 24376</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37080</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:20:55 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>