<bug>
          <bug_id>5767</bug_id>
          
          <creation_ts>2011-11-02 16:29:00 +0100</creation_ts>
          <short_desc>Failing tests in bom.request.* with Opera 12</short_desc>
          <delta_ts>2014-03-03 15:25:33 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>core.io</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>WORKSFORME</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>2.0.3</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Tristan Koch">tristan.koch</reporter>
          <assigned_to name="Martin Wittemann">martin.wittemann</assigned_to>
          
          <qa_contact name="Tristan Koch">tristan.koch</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>27374</commentid>
            <who name="Tristan Koch">tristan.koch</who>
            <bug_when>2011-11-02 16:29:22 +0100</bug_when>
            <thetext>Several tests in bom.request.Script.* and Jsonp.* related to network error fail. They pass in Opera 11.51.

qx.test.bom.request.Script:test: call onerror on network error
qx.test.bom.request.Script:test: not call onload when loading failed because of network error
qx.test.bom.request.Script:test: properties indicate failure when request failed</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>27435</commentid>
            <who name="Tristan Koch">tristan.koch</who>
            <bug_when>2011-11-07 15:24:10 +0100</bug_when>
            <thetext>Opera 12 receives a native load for unknown hosts (any kind of network error, I assume). This is indicated by the following test that passes (at least) in Chrome and Opera 11.50, but fails in Opera 12.

&quot;test: not receive load for unknown host&quot;: function() {
  var req = new qx.bom.request.Script();
  this.spy(req, &quot;onload&quot;);
  req.open(&quot;GET&quot;, &quot;http://fail.tld&quot;);
  req.send();
  this.wait(1000, function() {
    this.assertNotCalled(req.onload);
  }, this);
}</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31219</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2012-11-06 11:29:05 +0100</bug_when>
            <thetext>Seems like either Opera or we hav fixed these issues. Just gave it a try with the new Opera 12.10 and the tests run as expected.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>38789</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:25:33 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>