<bug>
          <bug_id>6912</bug_id>
          
          <creation_ts>2012-10-19 14:21:00 +0200</creation_ts>
          <short_desc>Test state inconsistency</short_desc>
          <delta_ts>2014-03-03 15:24:21 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>core.dev.testing</component>
          <version>2.0.1</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P2</priority>
          <bug_severity>minor</bug_severity>
          <target_milestone>2.0.2</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Daniel Wagner">daniel.wagner</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="Daniel Wagner">daniel.wagner</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>31005</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2012-10-19 14:21:50 +0200</bug_when>
            <thetext>If a unit test fails, is then run again and passes (for whatever reason), the test state changes to &quot;success&quot; as expected, but the result object still stores the exception from the initial run. In the UI, the test is then displayed in green but with a stack trace.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>31006</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2012-10-19 14:24:45 +0200</bug_when>
            <thetext>Fixed with
886a17db1f1286942e6567a47ced2729ad7d4f4e (master)
6cd76b654eeefb86bb017aa8cae9bcc203e26f59 (branch_2_0_x)</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>38353</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:24:21 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>