<bug>
          <bug_id>7121</bug_id>
          
          <creation_ts>2013-01-08 09:50:00 +0100</creation_ts>
          <short_desc>qx.log.Logger.__serialize runs into the error: Permission denied for &lt;https://mydomain.com&gt; to create wrapper for object of class UnnamedClass</short_desc>
          <delta_ts>2014-03-03 15:22:22 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>core</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>DUPLICATE</resolution>
          <dup_id>7105</dup_id>
          
          
          
          
          <priority>P3</priority>
          <bug_severity>minor</bug_severity>
          <target_milestone>2.1.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Uwe Stahl">uwe.stahl</reporter>
          <assigned_to name="Daniel Wagner">daniel.wagner</assigned_to>
          
          <qa_contact name="Martin Wittemann">martin.wittemann</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>31847</commentid>
            <who name="Uwe Stahl">uwe.stahl</who>
            <bug_when>2013-01-08 09:50:43 +0100</bug_when>
            <thetext>Our error logs show that our customers sometimes run into the following error:

Permission denied for &lt;https://mydomain.com&gt; to create wrapper for object of class UnnamedClass
at:
qx.log.Logger.__serialize
qx.log.Logger.__log
qx.log.Logger.error
qx.event.Registration.fireEvent 
qx.event.handler.Mouse.__fireEvent
qx.event.handler.Mouse._onButtonEvent
qx.event.GlobalError.observceMethod

The method qx.event.Registration.fireEvent contains the following lines of code:
} catch (exc) {
  qx.log.Logger.error(this, &quot;Dispatching event of type &quot; + evt.getType() + &quot; failed:&quot;, exc);

The problem is that the browser forbids the serialization of some fields of the exception object. This issue occurs with firefox 17 and firefox 16 on all operating systems (osx, win7, winxp).

Our application uses some iframes, but I am not sure whether these iframes are responsible for this issue.

We were not able to reproduce this issue, also we find this kind of error often in our logs.

I would recommend the following improvement to handle this issue:
Implement a try/catch-block in the method __serialize that catched this kind of problem.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>32026</commentid>
            <who name="Daniel Wagner">daniel.wagner</who>
            <bug_when>2013-01-28 17:46:53 +0100</bug_when>
            <thetext>Looks like this was caused by the problem described in bug #7105: The serializer treated DOMExceptions as maps rather than exceptions in Gecko. Trying to read the DOMException property &quot;location&quot; for serialization will cause the &quot;Permission denied&quot; exception. So this should now be fixed as well.

*** This bug has been marked as a duplicate of bug 7105 ***</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>37649</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:22:22 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>