<bug>
          <bug_id>762</bug_id>
          
          <creation_ts>2008-01-16 19:16:00 +0100</creation_ts>
          <short_desc>generator fails parsing certain arithmetic expressions</short_desc>
          <delta_ts>2014-03-03 15:27:45 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.generator.compiler</component>
          <version>0.7.3</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>WORKSFORME</resolution>
          
          
          
          
          
          <priority>P2</priority>
          <bug_severity>major</bug_severity>
          <target_milestone>0.8.2</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Evgeny Stambulchik">fnevgeny</reporter>
          <assigned_to name="Thomas Herchenroeder">thron7</assigned_to>
          
          <qa_contact name="qooxdoo bugs mailing list">qooxdoo-bugs</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>2778</commentid>
            <who name="Evgeny Stambulchik">fnevgeny</who>
            <bug_when>2008-01-16 19:16:49 +0100</bug_when>
            <thetext>Some arithmetic expressions cause parser/tokenizer to fail. E.g.

var one_quarter = 1.0/2/2;

results in

  File &quot;../../../../frontend/framework/tool/generator.py&quot;, line 1263, in ?
    main()
  File &quot;../../../../frontend/framework/tool/generator.py&quot;, line 325, in main
    argparser(sys.argv[1:])
  File &quot;../../../../frontend/framework/tool/generator.py&quot;, line 308, in argparser
    (fileDb, moduleDb) = load(options)
  File &quot;../../../../frontend/framework/tool/generator.py&quot;, line 350, in load
    (fileDb, moduleDb) = loader.indexAll(options)
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/loader.py&quot;, line 616, in indexAll
    resolveAutoDeps(fileDb, options)
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/loader.py&quot;, line 364, in resolveAutoDeps
    detectDeps(getTree(fileDb, fileId, options), fileEntry[&quot;optionalDeps&quot;], loadtimeDeps, runtimeDeps, fileId, fileDb, False)
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/loader.py&quot;, line 274, in getTree
    tree = treegenerator.createSyntaxTree(getTokens(fileDb, fileId, options))
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/loader.py&quot;, line 238, in getTokens
    tokens = tokenizer.parseStream(fileContent, fileId)
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/tokenizer.py&quot;, line 329, in parseStream
    content = parseFragmentLead(content, fragment, tokens)
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/tokenizer.py&quot;, line 237, in parseFragmentLead
    tokens.extend(parsePart(recoverEscape(content[0:pos])))
  File &quot;/local/src/test/qooxdoo-0.7.3-sdk/frontend/framework/tool/modules/tokenizer.py&quot;, line 188, in parsePart
    if (    (tokens[-1][&#39;detail&#39;] != &#39;int&#39;)   and
IndexError: list index out of range
make: *** [exec-script-source] Error 1</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>2920</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2008-03-28 17:41:05 +0100</bug_when>
            <thetext>accepted bug</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>2921</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2008-03-28 17:41:50 +0100</bug_when>
            <thetext>assigned to me</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>5069</commentid>
            <who name="Sebastian Werner">info</who>
            <bug_when>2008-09-03 20:04:39 +0200</bug_when>
            <thetext>To 0.8.1 because already assigned. Otherwise please free from the assigner and make target milestone unspecified again.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>5208</commentid>
            <who name="Evgeny Stambulchik">fnevgeny</who>
            <bug_when>2008-09-03 20:46:06 +0200</bug_when>
            <thetext>(In reply to comment #3)
&gt; To 0.8.1

I think the bug is not present in 0.8.0, so perhaps better to set the target to 0.7.4?</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>5345</commentid>
            <who name="Sebastian Werner">info</who>
            <bug_when>2008-09-06 16:07:11 +0200</bug_when>
            <thetext>To 0.8.1</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7518</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2009-02-02 10:03:54 +0100</bug_when>
            <thetext>I cannot repro the bug. The statement given in the description works fine for 
both trunk (0.8.2-pre) and 0.7.4. If the bug only shows up in a larger code 
context, reopen the bug and provide the context as an attachment.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7521</commentid>
            <who name="Evgeny Stambulchik">fnevgeny</who>
            <bug_when>2009-02-02 10:28:58 +0100</bug_when>
            <thetext>The bug has never been present in 0.8 (see my comment #4).  0.7.4 is now fine, confirmed.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>7530</commentid>
            <who name="Thomas Herchenroeder">thron7</who>
            <bug_when>2009-02-02 11:47:48 +0100</bug_when>
            <thetext>I knew your comment, but we always re-test a bug from the legacy branch in 
trunk, to make sure it doesn&#39;t somehow &quot;survive&quot; there. So my mentioning of it 
was more geared towards documenting that, than to you ;-). - Thanks for the 
confirmation.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>39578</commentid>
            <who name="Martin Wittemann">martin.wittemann</who>
            <bug_when>2014-03-03 15:27:45 +0100</bug_when>
            <thetext>Closed all bugs already shipped with a release.</thetext>
          </long_desc>
      
      

    </bug>