<bug>
          <bug_id>8026</bug_id>
          
          <creation_ts>2014-01-09 14:47:00 +0100</creation_ts>
          <short_desc>Grunt console output from the generator is different from a direct generator call</short_desc>
          <delta_ts>2014-01-10 12:22:31 +0100</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>1</classification_id>
          <classification>Unclassified</classification>
          <product>framework</product>
          <component>tool.grunt</component>
          <version>master</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          
          
          
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>3.5.1</target_milestone>
          
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Christian Hagendorn">christian.hagendorn</reporter>
          <assigned_to name="Richard Sternagel">richard.sternagel</assigned_to>
          
          <qa_contact name="Richard Sternagel">richard.sternagel</qa_contact>
          <cf_browser>---</cf_browser>
          

      

      

      

          <long_desc isprivate="0">
            <commentid>34731</commentid>
            <who name="Christian Hagendorn">christian.hagendorn</who>
            <bug_when>2014-01-09 14:47:01 +0100</bug_when>
            <thetext>When I use grunt the console output is deferent form the original generator call. In my case I refer to a not existing class. The original generator call shows a warning in the console output and the grunt call not. I would expect that the grunt call has the same console output as the direct generator call.

It looks for me that grunt doesn&#39;t include the stderr to console.

Have a look at the attached files to see the differences.</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>34734</commentid>
            <who name="Christian Hagendorn">christian.hagendorn</who>
            <bug_when>2014-01-09 16:33:03 +0100</bug_when>
            <thetext>Richi, I committed a fix on master with 2d93cab. The generator logs warnings on stderr but the child process dosen&#39;t consider the output. Could you please check my fix and apply it to the branch. Thanks</thetext>
          </long_desc>
          <long_desc isprivate="0">
            <commentid>34742</commentid>
            <who name="Richard Sternagel">richard.sternagel</who>
            <bug_when>2014-01-10 12:22:31 +0100</bug_when>
            <thetext>Works fine, thanks! 

branch_3_5_x: 9a02e41d46914a52b4679756658c06d4ba2a941e</thetext>
          </long_desc>
      
      

    </bug>